ALTER TABLE "Product"
ADD COLUMN "deliveryFee" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Gift"
ADD COLUMN "deliveryFee" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Souvenir"
ADD COLUMN "deliveryFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
