ALTER TABLE "Gift"
ADD COLUMN "stockQuantity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "priority" TEXT NOT NULL DEFAULT 'normal',
ADD COLUMN "flashSalePrice" DOUBLE PRECISION,
ADD COLUMN "flashSaleEndsAt" TIMESTAMP(3);

ALTER TABLE "Souvenir"
ADD COLUMN "stockQuantity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "priority" TEXT NOT NULL DEFAULT 'normal',
ADD COLUMN "flashSalePrice" DOUBLE PRECISION,
ADD COLUMN "flashSaleEndsAt" TIMESTAMP(3);
